on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: make build
    - name: Generate examples
      env:
        PROTO_FLAGS: "--plugin=protoc-gen-toit=$PWD/protoc-gen-toit"
      run: make clean gen_examples
